Repository vulncheck-oss/go-exploit, pull requests merged in 2023-06, with the labels that each got.

#8 Add protocol.MultipartCreateForm
  protocol/httphelper.go
Labels: enhancement

#7 Switch to crypto/rand and add int() rand functions
  random/random.go
  random/random_test.go
Labels: enhancement, good first issue

#9 Randomize class name in java.FixReverseShell
  go.mod
  go.sum
  java/javaclass.go
  transform/encode.go
  transform/encode_test.go
Labels: enhancement

#11 Update docs and fix wording on lhost/lport flags
  cli/commandline.go
  docs/c2.md
Labels: documentation

#12 Add WindowsCurlHTTPDownloadAndExecute payload
  payload/download.go
  payload/download_test.go
Labels: enhancement

#15 Add protocol.ParseCookies
  protocol/httphelper.go
  protocol/httphelper_test.go
Labels: enhancement
