Repository vulncheck-oss/go-exploit, pull requests merged in 2024-10, with the labels that each got.

#242 Fix bind shell to use -rhost
  framework.go
Labels: bug, regression

#244 Added an extremely minimal PHP GET webshell
  java/javaclass.go
  payload/webshell/php.go
  payload/webshell/webshell.go
  payload/webshell/webshell_test.go
Labels: webshell

#249 Fix RocketMQ artificial cap check
  protocol/rocketmq/remoting.go
  protocol/rocketmq/remoting_test.go
Labels: bug
